version: '3.8'

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    container_name: pg
    volumes:
      - pg:/var/lib/postgresql/data
    stdin_open: true
    tty: true

volumes:
  pg:
