version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    container_name: pg_prod
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nest-pg-gql:0.1.0
    container_name: prod_app
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
