version: '3.8'

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    container_name: pg
    volumes:
      - ./pg/data:/var/lib/postgresql/data
