version: '3.8'

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      DB_USERNAME: 'postgres'
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: drello_db
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    image: drglasdou/drello:0.0.1
    container_name: drello_api
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      DB_PASSWORD: 'password'
      DB_NAME: 'Drello'
      DB_PORT: '5432'
      DB_HOST: db
      DB_USERNAME: 'postgres'
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: '/var/lib/postgresql/data/pgdata'
      PORT: '3000'
      STATE: 'dev'
      JWT_SECRET: 'VQZ8cmf8naf_cwd.ukb'
